### ISSUE TITLE
funny

### ISSUE THREAD

**Issue by min89xd** [grafexteam/fnf-grafex#12]
### What feature do you want to get added on the base engine?

update to latest psych commit

**Comment by MemeHoovy** [comment]
> ### What feature do you want to get added on the base engine?
> update to latest psych commit

do you understand how hard that would be?

**Comment by min89xd** [comment]
> > ### What feature do you want to get added on the base engine?
> > update to latest psych commit
> 
> do you understand how hard that would be?

yes but I think it would be a good addition because the git version is very stable

**Comment by MemeHoovy** [comment]
> > > ### What feature do you want to get added on the base engine?
> > > update to latest psych commit
> > 
> > 
> > do you understand how hard that would be?
> 
> yes but I think it would be a good addition because the git version is very stable

I'm sure they can do that in their own time
