### ISSUE TITLE
Weird issue with funkinlua,hx

### ISSUE THREAD

**Issue by magistricide** [grafexteam/fnf-grafex#13]
### Describe your problem here.

this popped up
![Screenshot_465](https://user-images.githubusercontent.com/114634489/194671938-7d0b363c-4533-4c91-94a0-e4d9b99c10f3.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing was edited yet

**Comment by MemeHoovy** [comment]
have you already done this?
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

**Comment by magistricide** [comment]
> have you already done this? haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit

yes i have

**Comment by MemeHoovy** [comment]
maybe you shouldn't use the raw branch since it's pretty unstable

**Comment by magistricide** [comment]
> maybe you shouldn't use the raw branch since it's pretty unstable

alright
